Anreg
================
Dama
2026-02-04

# Input Data

Jika data berupa csv, maka tidak perlu pemanggilan `library(readxl)`
karena R sudah memiliki fungsi bawaan terhadap hal tersebut. Apabila
file .csv pada software excel ditunjukkan dengan delimiter “,” maka
dapat menggunakan fungsi `read.csv`, apabila delimiter berupa “;” maka
dapat menggunakan fungsi `read.csv2`.

``` r
library(readxl)
library(ggplot2)

data_anreg <- read_excel("C:\\Users\\USER\\Documents\\A MATKUL IPB/Semester 4/Anreg/Bahan data/NSC-2025.xlsx")

as.data.frame(data_anreg)
```

    ##             Kabupaten/Kota Indeks Pembangunan Manusia Rata-Rata Lama Sekolah
    ## 1         Kepulauan Seribu                      76.69                   9.26
    ## 2     Kota Jakarta Selatan                      87.57                  11.95
    ## 3       Kota Jakarta Timur                      84.76                  11.99
    ## 4       Kota Jakarta Pusat                      83.75                  11.61
    ## 5       Kota Jakarta Barat                      84.40                  11.24
    ## 6       Kota Jakarta Utara                      82.13                  10.85
    ## 7                    Bogor                      73.63                   8.89
    ## 8                 Sukabumi                      70.18                   7.75
    ## 9                  Cianjur                      68.89                   7.91
    ## 10                 Bandung                      74.59                   9.45
    ## 11                   Garut                      69.91                   8.31
    ## 12             Tasikmalaya                      69.98                   8.32
    ## 13                  Ciamis                      73.64                   8.33
    ## 14                Kuningan                      71.56                   8.18
    ## 15                 Cirebon                      72.30                   8.06
    ## 16              Majalengka                      71.37                   7.99
    ## 17                Sumedang                      74.57                   8.86
    ## 18               Indramayu                      70.72                   7.45
    ## 19                  Subang                      72.05                   7.88
    ## 20              Purwakarta                      73.99                   8.40
    ## 21                Karawang                      73.82                   8.54
    ## 22                  Bekasi                      76.80                  10.19
    ## 23           Bandung Barat                      70.77                   8.57
    ## 24             Pangandaran                      71.03                   8.47
    ## 25              Kota Bogor                      79.03                  10.79
    ## 26           Kota Sukabumi                      77.69                  10.44
    ## 27            Kota Bandung                      83.75                  11.05
    ## 28            Kota Cirebon                      78.09                  10.66
    ## 29             Kota Bekasi                      83.55                  11.90
    ## 30              Kota Depok                      83.05                  11.58
    ## 31             Kota Cimahi                      80.30                  11.47
    ## 32        Kota Tasikmalaya                      76.03                   9.86
    ## 33             Kota Banjar                      75.01                   9.15
    ## 34                 Cilacap                      72.55                   7.40
    ## 35                Banyumas                      74.52                   7.91
    ## 36             Purbalingga                      70.97                   7.36
    ## 37            Banjarnegara                      69.62                   6.87
    ## 38                 Kebumen                      72.48                   7.87
    ## 39               Purworejo                      75.16                   8.65
    ## 40                Wonosobo                      70.63                   6.90
    ## 41                Magelang                      72.10                   7.83
    ## 42                Boyolali                      75.96                   8.17
    ## 43                  Klaten                      78.16                   9.29
    ## 44               Sukoharjo                      79.30                  10.01
    ## 45                Wonogiri                      72.54                   7.68
    ## 46             Karanganyar                      78.11                   9.26
    ## 47                  Sragen                      75.53                   7.88
    ## 48                Grobogan                      72.02                   7.29
    ## 49                   Blora                      71.42                   7.26
    ## 50                 Rembang                      72.53                   7.73
    ## 51                    Pati                      74.10                   7.82
    ## 52                   Kudus                      77.21                   9.35
    ## 53                  Jepara                      74.32                   8.27
    ## 54                   Demak                      74.57                   8.28
    ## 55                Semarang                      75.67                   8.16
    ## 56              Temanggung                      71.86                   7.53
    ## 57                  Kendal                      74.34                   7.74
    ## 58                  Batang                      70.73                   7.08
    ## 59              Pekalongan                      71.95                   7.48
    ## 60                Pemalang                      68.65                   6.56
    ## 61                   Tegal                      71.70                   7.36
    ## 62                  Brebes                      70.18                   6.41
    ## 63           Kota Magelang                      82.15                  11.43
    ## 64          Kota Surakarta                      84.41                  11.25
    ## 65           Kota Salatiga                      85.72                  11.48
    ## 66           Kota Semarang                      85.24                  11.05
    ## 67         Kota Pekalongan                      77.21                   9.34
    ## 68              Kota Tegal                      77.50                   9.28
    ## 69             Kulon Progo                      76.18                   9.20
    ## 70                  Bantul                      82.05                   9.81
    ## 71            Gunung Kidul                      72.14                   7.35
    ## 72                  Sleman                      85.71                  11.33
    ## 73         Kota Yogyakarta                      89.10                  12.12
    ## 74                 Pacitan                      71.49                   7.90
    ## 75                Ponorogo                      73.70                   7.80
    ## 76              Trenggalek                      72.47                   7.92
    ## 77             Tulungagung                      75.13                   8.68
    ## 78                  Blitar                      73.44                   7.87
    ## 79                  Kediri                      75.18                   8.26
    ## 80                  Malang                      73.53                   7.80
    ## 81                Lumajang                      70.31                   7.27
    ## 82                  Jember                      70.93                   6.54
    ## 83              Banyuwangi                      74.30                   7.78
    ## 84               Bondowoso                      71.22                   6.53
    ## 85               Situbondo                      71.22                   6.93
    ## 86             Probolinggo                      70.85                   6.31
    ## 87                Pasuruan                      72.36                   7.46
    ## 88                Sidoarjo                      82.67                  10.91
    ## 89               Mojokerto                      76.69                   9.13
    ## 90                 Jombang                      75.67                   8.78
    ## 91                 Nganjuk                      75.24                   8.25
    ## 92                  Madiun                      74.81                   8.20
    ## 93                 Magetan                      76.77                   8.69
    ## 94                   Ngawi                      73.91                   7.84
    ## 95              Bojonegoro                      72.75                   7.59
    ## 96                   Tuban                      72.31                   7.53
    ## 97                Lamongan                      75.90                   8.48
    ## 98                  Gresik                      78.93                  10.03
    ## 99               Bangkalan                      67.33                   6.01
    ## 100                Sampang                      66.72                   5.08
    ## 101              Pamekasan                      70.85                   7.17
    ## 102                Sumenep                      69.78                   6.10
    ## 103            Kota Kediri                      81.88                  10.92
    ## 104            Kota Blitar                      81.44                  10.82
    ## 105            Kota Malang                      84.68                  11.14
    ## 106       Kota Probolinggo                      77.79                   9.72
    ## 107          Kota Pasuruan                      78.90                   9.94
    ## 108         Kota Mojokerto                      81.76                  11.38
    ## 109            Kota Madiun                      84.51                  12.11
    ## 110          Kota Surabaya                      84.69                  10.89
    ## 111              Kota Batu                      79.69                   9.87
    ## 112             Pandeglang                      70.88                   7.16
    ## 113                  Lebak                      68.33                   6.61
    ## 114              Tangerang                      76.19                   9.06
    ## 115                 Serang                      73.28                   7.88
    ## 116         Kota Tangerang                      81.53                  11.14
    ## 117           Kota Cilegon                      78.83                  10.39
    ## 118            Kota Serang                      76.90                   8.93
    ## 119 Kota Tangerang Selatan                      84.16                  11.86
    ##     PDRB ADHK (MILYAR RUPIAH) Persentase Penduduk Miskin
    ## 1                     3268.50                      13.03
    ## 2                   500422.70                       3.03
    ## 3                   362068.10                       4.09
    ## 4                   532606.90                       4.63
    ## 5                   383113.10                       3.94
    ## 6                   380461.10                       6.44
    ## 7                   185882.34                       7.05
    ## 8                    55723.92                       6.87
    ## 9                    38208.18                      10.14
    ## 10                   97509.91                       6.19
    ## 11                   46270.92                       9.68
    ## 12                   28879.68                      10.23
    ## 13                   26360.94                       7.39
    ## 14                   20507.27                      11.88
    ## 15                   39418.27                      11.00
    ## 16                   27438.93                      10.82
    ## 17                   27965.76                       9.10
    ## 18                   68701.96                      11.93
    ## 19                   33126.46                       9.49
    ## 20                   54142.29                       8.41
    ## 21                  194903.10                       7.86
    ## 22                  293664.79                       4.80
    ## 23                   36793.68                      10.49
    ## 24                    9324.31                       8.75
    ## 25                   38964.67                       6.53
    ## 26                   10303.16                       7.20
    ## 27                  233053.79                       3.87
    ## 28                   19884.06                       9.02
    ## 29                   81251.61                       4.01
    ## 30                   58241.86                       2.34
    ## 31                   27296.93                       4.39
    ## 32                   18709.87                      11.10
    ## 33                    3883.98                       5.85
    ## 34                  104540.67                      10.68
    ## 35                   47795.71                      11.95
    ## 36                   20422.61                      14.18
    ## 37                   18051.84                      14.71
    ## 38                   23837.83                      15.71
    ## 39                   15745.98                      10.87
    ## 40                   16109.38                      15.28
    ## 41                   27538.21                      10.83
    ## 42                   27556.18                       9.63
    ## 43                   33568.92                      12.04
    ## 44                   32187.41                       7.47
    ## 45                   24728.69                      10.71
    ## 46                   31883.10                       9.59
    ## 47                   32084.08                      12.41
    ## 48                   23591.06                      11.43
    ## 49                   19776.06                      11.42
    ## 50                   16248.58                      14.02
    ## 51                   36780.74                       9.17
    ## 52                   75010.79                       7.23
    ## 53                   25482.07                       6.09
    ## 54                   21894.60                      11.89
    ## 55                   41529.40                       6.96
    ## 56                   17855.60                       8.67
    ## 57                   37201.45                       9.35
    ## 58                   18693.22                       8.73
    ## 59                   19283.06                       8.95
    ## 60                   21778.06                      14.92
    ## 61                   29444.38                       6.81
    ## 62                   38546.98                      15.60
    ## 63                    7668.79                       5.94
    ## 64                   42897.32                       8.31
    ## 65                   11505.05                       4.57
    ## 66                  170947.72                       4.03
    ## 67                    8928.80                       6.71
    ## 68                   13119.70                       7.64
    ## 69                   10426.23                      15.62
    ## 70                   22964.66                      11.66
    ## 71                   16506.42                      15.18
    ## 72                   41560.00                       7.46
    ## 73                   32964.35                       6.26
    ## 74                   12775.80                      13.08
    ## 75                   16622.80                       9.11
    ## 76                   14881.60                      10.50
    ## 77                   31703.90                       6.28
    ## 78                   29493.80                       8.16
    ## 79                   33787.60                       9.95
    ## 80                   79500.90                       8.98
    ## 81                   25929.90                       8.65
    ## 82                   62897.20                       9.01
    ## 83                   63693.60                       6.54
    ## 84                   15809.30                      12.60
    ## 85                   15741.80                      11.51
    ## 86                   27153.10                      16.45
    ## 87                  125622.80                       8.63
    ## 88                  169867.80                       4.53
    ## 89                   70527.70                       9.37
    ## 90                   33230.50                       8.60
    ## 91                   21614.90                      10.17
    ## 92                   15593.20                      10.63
    ## 93                   15259.90                       9.32
    ## 94                   15596.00                      13.81
    ## 95                   64367.40                      11.69
    ## 96                   51913.40                      14.36
    ## 97                   32186.00                      12.16
    ## 98                  119274.40                      10.32
    ## 99                   17497.50                      18.66
    ## 100                  14925.30                      20.83
    ## 101                  13245.30                      13.41
    ## 102                  27234.40                      17.78
    ## 103                  94774.10                       6.51
    ## 104                   5746.40                       6.75
    ## 105                  63373.30                       3.91
    ## 106                   9893.30                       6.18
    ## 107                   6998.70                       6.32
    ## 108                   5686.80                       5.57
    ## 109                  12438.90                       4.38
    ## 110                 485448.90                       3.96
    ## 111                  13588.10                       3.06
    ## 112                  21928.59                       9.18
    ## 113                  23377.24                       8.44
    ## 114                 113998.20                       6.55
    ## 115                  63255.33                       4.51
    ## 116                 125060.30                       5.43
    ## 117                  88628.11                       3.75
    ## 118                  26863.08                       5.65
    ## 119                  73052.84                       2.36
    ##     Persentase Akses Sanitasi Layak
    ## 1                             89.10
    ## 2                             92.61
    ## 3                             97.15
    ## 4                             90.30
    ## 5                             94.94
    ## 6                             91.39
    ## 7                             67.18
    ## 8                             51.90
    ## 9                             63.30
    ## 10                            69.12
    ## 11                            49.99
    ## 12                            54.68
    ## 13                            77.12
    ## 14                            84.64
    ## 15                            87.92
    ## 16                            83.61
    ## 17                            77.32
    ## 18                            97.27
    ## 19                            90.29
    ## 20                            83.01
    ## 21                            85.99
    ## 22                            89.16
    ## 23                            54.02
    ## 24                            90.30
    ## 25                            71.49
    ## 26                            45.88
    ## 27                            55.90
    ## 28                            95.38
    ## 29                            99.08
    ## 30                            98.76
    ## 31                            76.44
    ## 32                            53.16
    ## 33                            91.07
    ## 34                            83.25
    ## 35                            83.25
    ## 36                            82.01
    ## 37                            52.40
    ## 38                            93.43
    ## 39                            84.64
    ## 40                            63.81
    ## 41                            83.77
    ## 42                            88.26
    ## 43                            97.86
    ## 44                            97.08
    ## 45                            96.25
    ## 46                            98.54
    ## 47                            95.71
    ## 48                            93.94
    ## 49                            90.81
    ## 50                            94.89
    ## 51                            96.33
    ## 52                            95.90
    ## 53                            68.05
    ## 54                            95.13
    ## 55                            86.32
    ## 56                            71.77
    ## 57                            83.05
    ## 58                            65.92
    ## 59                            82.61
    ## 60                            84.32
    ## 61                            87.09
    ## 62                            85.85
    ## 63                            88.55
    ## 64                            85.07
    ## 65                            96.28
    ## 66                            95.83
    ## 67                            89.38
    ## 68                            92.48
    ## 69                            97.16
    ## 70                            96.46
    ## 71                            97.63
    ## 72                            96.43
    ## 73                            96.27
    ## 74                            81.26
    ## 75                            92.57
    ## 76                            84.66
    ## 77                            87.76
    ## 78                            86.16
    ## 79                            94.94
    ## 80                            86.74
    ## 81                            82.45
    ## 82                            67.46
    ## 83                            86.22
    ## 84                            62.10
    ## 85                            62.66
    ## 86                            66.39
    ## 87                            86.36
    ## 88                            97.95
    ## 89                            91.14
    ## 90                            96.13
    ## 91                            90.96
    ## 92                            91.47
    ## 93                            89.99
    ## 94                            82.99
    ## 95                            96.43
    ## 96                            85.12
    ## 97                            95.88
    ## 98                            93.22
    ## 99                            50.31
    ## 100                           87.24
    ## 101                           72.94
    ## 102                           73.31
    ## 103                           95.39
    ## 104                           95.93
    ## 105                           87.84
    ## 106                           91.59
    ## 107                           95.52
    ## 108                           98.56
    ## 109                           95.19
    ## 110                           97.69
    ## 111                           96.39
    ## 112                           63.66
    ## 113                           70.23
    ## 114                           89.38
    ## 115                           85.31
    ## 116                           96.93
    ## 117                           97.10
    ## 118                           92.71
    ## 119                           99.34
    ##     Kontribusi Sektor Industri Pengolahan teradap PDRB/PDB  (%)
    ## 1                                                          4.06
    ## 2                                                          1.38
    ## 3                                                         26.73
    ## 4                                                          0.84
    ## 5                                                          5.30
    ## 6                                                         30.31
    ## 7                                                         51.65
    ## 8                                                         17.13
    ## 9                                                          7.29
    ## 10                                                        52.91
    ## 11                                                         9.44
    ## 12                                                         8.33
    ## 13                                                         7.29
    ## 14                                                         2.27
    ## 15                                                        20.49
    ## 16                                                        25.94
    ## 17                                                        19.32
    ## 18                                                        43.89
    ## 19                                                        12.76
    ## 20                                                        57.60
    ## 21                                                        69.91
    ## 22                                                        76.96
    ## 23                                                        40.85
    ## 24                                                         4.87
    ## 25                                                        18.39
    ## 26                                                         4.87
    ## 27                                                        18.29
    ## 28                                                        10.09
    ## 29                                                        33.05
    ## 30                                                        29.16
    ## 31                                                        44.83
    ## 32                                                        13.41
    ## 33                                                        10.29
    ## 34                                                        55.46
    ## 35                                                        26.40
    ## 36                                                        28.27
    ## 37                                                        16.57
    ## 38                                                        22.69
    ## 39                                                        20.06
    ## 40                                                        17.72
    ## 41                                                        24.46
    ## 42                                                        31.48
    ## 43                                                        38.55
    ## 44                                                        38.15
    ## 45                                                        19.25
    ## 46                                                        46.97
    ## 47                                                        39.76
    ## 48                                                        14.79
    ## 49                                                        10.91
    ## 50                                                        24.39
    ## 51                                                        28.78
    ## 52                                                        77.71
    ## 53                                                        34.01
    ## 54                                                        31.66
    ## 55                                                        38.71
    ## 56                                                        25.53
    ## 57                                                        41.70
    ## 58                                                        34.89
    ## 59                                                        29.66
    ## 60                                                        22.51
    ## 61                                                        36.45
    ## 62                                                        19.31
    ## 63                                                        16.49
    ## 64                                                         8.55
    ## 65                                                        33.14
    ## 66                                                        28.35
    ## 67                                                        19.86
    ## 68                                                        16.68
    ## 69                                                        10.11
    ## 70                                                        14.08
    ## 71                                                         8.38
    ## 72                                                        12.37
    ## 73                                                        12.02
    ## 74                                                         7.71
    ## 75                                                         9.62
    ## 76                                                        19.42
    ## 77                                                        24.16
    ## 78                                                        15.46
    ## 79                                                        23.06
    ## 80                                                        32.71
    ## 81                                                        23.29
    ## 82                                                        21.01
    ## 83                                                        12.94
    ## 84                                                        25.21
    ## 85                                                        20.97
    ## 86                                                        27.36
    ## 87                                                        60.65
    ## 88                                                        48.57
    ## 89                                                        57.93
    ## 90                                                        22.24
    ## 91                                                        16.31
    ## 92                                                        14.57
    ## 93                                                        12.28
    ## 94                                                        10.11
    ## 95                                                         6.95
    ## 96                                                        30.21
    ## 97                                                        12.23
    ## 98                                                        51.25
    ## 99                                                         3.04
    ## 100                                                        4.18
    ## 101                                                        7.74
    ## 102                                                        6.73
    ## 103                                                       79.64
    ## 104                                                        9.90
    ## 105                                                       27.09
    ## 106                                                       14.63
    ## 107                                                       19.81
    ## 108                                                        9.34
    ## 109                                                       13.63
    ## 110                                                       19.07
    ## 111                                                        6.29
    ## 112                                                        7.19
    ## 113                                                        9.54
    ## 114                                                       33.74
    ## 115                                                       46.69
    ## 116                                                       26.98
    ## 117                                                       56.16
    ## 118                                                        4.61
    ## 119                                                        8.09
    ##     Pertumbuhan Ekonomi Sektor Industri Pengolahan Indeks Pembangunan Gender
    ## 1                                             0.37                     93.62
    ## 2                                             3.74                     97.30
    ## 3                                             2.13                     95.90
    ## 4                                             0.01                     96.24
    ## 5                                             2.16                     95.66
    ## 6                                             0.52                     94.43
    ## 7                                             3.94                     90.98
    ## 8                                             7.72                     89.38
    ## 9                                             5.48                     86.22
    ## 10                                            6.21                     95.10
    ## 11                                            9.45                     84.24
    ## 12                                            9.57                     87.64
    ## 13                                            3.27                     88.29
    ## 14                                            5.83                     88.00
    ## 15                                            5.87                     85.43
    ## 16                                            9.02                     87.98
    ## 17                                           -1.13                     96.22
    ## 18                                            0.00                     89.78
    ## 19                                            4.86                     92.11
    ## 20                                            3.46                     87.96
    ## 21                                            2.91                     91.98
    ## 22                                            4.93                     90.18
    ## 23                                            3.14                     81.59
    ## 24                                            2.53                     91.22
    ## 25                                            2.45                     92.34
    ## 26                                            5.97                     93.24
    ## 27                                            0.77                     95.38
    ## 28                                            1.27                     96.59
    ## 29                                            2.96                     94.28
    ## 30                                            5.00                     94.26
    ## 31                                            2.81                     92.78
    ## 32                                            5.46                     92.98
    ## 33                                            3.91                     88.93
    ## 34                                            1.06                     87.82
    ## 35                                            5.05                     89.64
    ## 36                                            4.25                     93.92
    ## 37                                            4.37                     95.11
    ## 38                                            6.00                     93.39
    ## 39                                            4.86                     95.24
    ## 40                                            1.42                     92.94
    ## 41                                            6.54                     92.93
    ## 42                                            6.50                     94.76
    ## 43                                            5.37                     95.99
    ## 44                                            3.63                     97.87
    ## 45                                            6.49                     92.27
    ## 46                                            5.40                     97.13
    ## 47                                            4.90                     92.57
    ## 48                                            5.55                     86.40
    ## 49                                            5.16                     85.85
    ## 50                                            5.61                     88.45
    ## 51                                            6.26                     92.46
    ## 52                                            1.76                     93.92
    ## 53                                            2.97                     91.63
    ## 54                                            4.77                     91.19
    ## 55                                            3.86                     96.63
    ## 56                                            3.05                     96.13
    ## 57                                            4.36                     94.29
    ## 58                                            5.29                     92.59
    ## 59                                            2.96                     92.87
    ## 60                                            4.34                     87.30
    ## 61                                            3.87                     88.72
    ## 62                                            6.16                     87.54
    ## 63                                            4.09                     96.66
    ## 64                                            2.86                     97.43
    ## 65                                            3.77                     95.49
    ## 66                                            2.43                     96.28
    ## 67                                            0.79                     95.49
    ## 68                                            5.19                     93.92
    ## 69                                            4.33                     95.86
    ## 70                                            3.75                     96.05
    ## 71                                            3.76                     87.13
    ## 72                                            2.88                     97.11
    ## 73                                            3.51                     99.25
    ## 74                                            7.14                     87.11
    ## 75                                            7.49                     95.16
    ## 76                                            6.68                     93.20
    ## 77                                            7.11                     95.99
    ## 78                                            6.62                     94.10
    ## 79                                            7.85                     94.01
    ## 80                                            4.68                     89.53
    ## 81                                            7.66                     90.16
    ## 82                                            5.59                     86.35
    ## 83                                            7.05                     88.09
    ## 84                                            4.48                     91.49
    ## 85                                            6.70                     87.99
    ## 86                                            7.16                     87.11
    ## 87                                            5.47                     91.94
    ## 88                                            5.18                     95.45
    ## 89                                            5.89                     92.41
    ## 90                                            6.65                     91.32
    ## 91                                            6.67                     94.92
    ## 92                                            5.01                     93.33
    ## 93                                            4.50                     95.05
    ## 94                                            6.09                     93.79
    ## 95                                            8.72                     92.22
    ## 96                                            1.83                     89.59
    ## 97                                            7.66                     90.70
    ## 98                                            6.32                     91.63
    ## 99                                            9.15                     88.09
    ## 100                                           7.54                     87.52
    ## 101                                           6.32                     87.60
    ## 102                                           8.26                     83.03
    ## 103                                           2.94                     95.99
    ## 104                                           5.11                     98.03
    ## 105                                           5.13                     97.02
    ## 106                                           3.92                     97.26
    ## 107                                           3.52                     97.82
    ## 108                                           3.44                     95.20
    ## 109                                           6.36                     95.92
    ## 110                                           5.48                     95.75
    ## 111                                           8.60                     91.50
    ## 112                                           6.67                     87.93
    ## 113                                           5.81                     81.69
    ## 114                                           4.61                     92.63
    ## 115                                           5.65                     93.52
    ## 116                                           4.03                     95.91
    ## 117                                           5.05                     89.17
    ## 118                                           6.45                     93.59
    ## 119                                           7.96                     95.29
    ##     Tingkat Partisipasi Angkatan Kerja (TPAK)
    ## 1                                       72.58
    ## 2                                       64.81
    ## 3                                       64.49
    ## 4                                       65.12
    ## 5                                       64.12
    ## 6                                       67.77
    ## 7                                       66.30
    ## 8                                       69.75
    ## 9                                       72.63
    ## 10                                      67.22
    ## 11                                      71.34
    ## 12                                      68.76
    ## 13                                      68.14
    ## 14                                      65.84
    ## 15                                      69.27
    ## 16                                      69.64
    ## 17                                      69.24
    ## 18                                      66.43
    ## 19                                      71.71
    ## 20                                      66.62
    ## 21                                      63.67
    ## 22                                      65.11
    ## 23                                      68.30
    ## 24                                      80.12
    ## 25                                      67.35
    ## 26                                      62.58
    ## 27                                      67.93
    ## 28                                      68.55
    ## 29                                      65.58
    ## 30                                      62.89
    ## 31                                      66.52
    ## 32                                      68.92
    ## 33                                      67.22
    ## 34                                      67.95
    ## 35                                      68.03
    ## 36                                      74.47
    ## 37                                      73.38
    ## 38                                      77.37
    ## 39                                      73.72
    ## 40                                      74.97
    ## 41                                      77.72
    ## 42                                      75.25
    ## 43                                      74.24
    ## 44                                      68.21
    ## 45                                      77.75
    ## 46                                      74.57
    ## 47                                      74.54
    ## 48                                      76.56
    ## 49                                      73.51
    ## 50                                      74.50
    ## 51                                      76.75
    ## 52                                      75.53
    ## 53                                      71.94
    ## 54                                      72.36
    ## 55                                      79.29
    ## 56                                      78.06
    ## 57                                      76.85
    ## 58                                      77.91
    ## 59                                      76.38
    ## 60                                      72.24
    ## 61                                      73.49
    ## 62                                      71.92
    ## 63                                      67.66
    ## 64                                      67.42
    ## 65                                      70.72
    ## 66                                      69.88
    ## 67                                      76.06
    ## 68                                      69.61
    ## 69                                      78.57
    ## 70                                      74.87
    ## 71                                      76.87
    ## 72                                      73.27
    ## 73                                      70.56
    ## 74                                      86.62
    ## 75                                      78.75
    ## 76                                      80.08
    ## 77                                      75.57
    ## 78                                      72.36
    ## 79                                      71.31
    ## 80                                      72.90
    ## 81                                      70.86
    ## 82                                      73.76
    ## 83                                      75.36
    ## 84                                      75.10
    ## 85                                      76.66
    ## 86                                      73.18
    ## 87                                      75.31
    ## 88                                      68.37
    ## 89                                      73.94
    ## 90                                      71.88
    ## 91                                      69.79
    ## 92                                      72.34
    ## 93                                      77.04
    ## 94                                      75.73
    ## 95                                      73.86
    ## 96                                      74.55
    ## 97                                      74.80
    ## 98                                      71.61
    ## 99                                      70.48
    ## 100                                     73.62
    ## 101                                     79.13
    ## 102                                     78.16
    ## 103                                     70.74
    ## 104                                     70.44
    ## 105                                     67.52
    ## 106                                     67.55
    ## 107                                     72.72
    ## 108                                     72.68
    ## 109                                     70.60
    ## 110                                     70.49
    ## 111                                     73.53
    ## 112                                     66.92
    ## 113                                     72.82
    ## 114                                     65.88
    ## 115                                     67.77
    ## 116                                     66.02
    ## 117                                     60.83
    ## 118                                     69.10
    ## 119                                     58.13
    ##     Tingkat Pengangguran Terbuka (TPT)
    ## 1                                 7.93
    ## 2                                 5.22
    ## 3                                 6.95
    ## 4                                 6.24
    ## 5                                 6.18
    ## 6                                 6.18
    ## 7                                 7.34
    ## 8                                 7.11
    ## 9                                 5.99
    ## 10                                6.36
    ## 11                                6.96
    ## 12                                3.74
    ## 13                                3.37
    ## 14                                7.78
    ## 15                                6.74
    ## 16                                4.01
    ## 17                                6.16
    ## 18                                6.25
    ## 19                                6.73
    ## 20                                7.34
    ## 21                                8.04
    ## 22                                8.82
    ## 23                                6.70
    ## 24                                1.58
    ## 25                                8.13
    ## 26                                8.34
    ## 27                                7.40
    ## 28                                6.29
    ## 29                                7.82
    ## 30                                6.27
    ## 31                                8.97
    ## 32                                6.49
    ## 33                                5.44
    ## 34                                7.83
    ## 35                                6.18
    ## 36                                4.96
    ## 37                                5.57
    ## 38                                5.07
    ## 39                                3.89
    ## 40                                4.02
    ## 41                                3.55
    ## 42                                3.16
    ## 43                                3.97
    ## 44                                3.65
    ## 45                                2.40
    ## 46                                3.47
    ## 47                                3.53
    ## 48                                3.23
    ## 49                                3.67
    ## 50                                2.84
    ## 51                                3.87
    ## 52                                3.19
    ## 53                                3.34
    ## 54                                4.75
    ## 55                                3.73
    ## 56                                2.35
    ## 57                                5.01
    ## 58                                5.67
    ## 59                                3.30
    ## 60                                6.63
    ## 61                                7.53
    ## 62                                8.35
    ## 63                                4.40
    ## 64                                4.61
    ## 65                                3.86
    ## 66                                5.82
    ## 67                                4.91
    ## 68                                5.88
    ## 69                                2.01
    ## 70                                3.62
    ## 71                                2.16
    ## 72                                4.13
    ## 73                                5.80
    ## 74                                1.56
    ## 75                                4.19
    ## 76                                3.90
    ## 77                                4.12
    ## 78                                4.77
    ## 79                                5.10
    ## 80                                5.13
    ## 81                                3.28
    ## 82                                3.23
    ## 83                                4.03
    ## 84                                3.63
    ## 85                                3.15
    ## 86                                3.00
    ## 87                                5.02
    ## 88                                6.49
    ## 89                                3.87
    ## 90                                3.75
    ## 91                                3.87
    ## 92                                4.34
    ## 93                                3.28
    ## 94                                2.40
    ## 95                                4.42
    ## 96                                4.28
    ## 97                                4.34
    ## 98                                6.45
    ## 99                                5.35
    ## 100                               2.50
    ## 101                               1.64
    ## 102                               1.69
    ## 103                               3.91
    ## 104                               5.11
    ## 105                               6.10
    ## 106                               4.44
    ## 107                               4.63
    ## 108                               3.76
    ## 109                               4.30
    ## 110                               4.91
    ## 111                               3.63
    ## 112                               8.09
    ## 113                               6.23
    ## 114                               6.06
    ## 115                               9.18
    ## 116                               5.92
    ## 117                               6.08
    ## 118                               7.12
    ## 119                               5.09

``` r
colnames(data_anreg) <- c("Kabupaten/Kota", "Y", paste0("X", 1:9))
head(data_anreg)
```

    ## # A tibble: 6 × 11
    ##   `Kabupaten/Kota`      Y    X1     X2    X3    X4    X5    X6    X7    X8    X9
    ##   <chr>             <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
    ## 1 Kepulauan Seribu   76.7  9.26 3.27e3 13.0   89.1  4.06  0.37  93.6  72.6  7.93
    ## 2 Kota Jakarta Sel…  87.6 12.0  5.00e5  3.03  92.6  1.38  3.74  97.3  64.8  5.22
    ## 3 Kota Jakarta Tim…  84.8 12.0  3.62e5  4.09  97.2 26.7   2.13  95.9  64.5  6.95
    ## 4 Kota Jakarta Pus…  83.8 11.6  5.33e5  4.63  90.3  0.84  0.01  96.2  65.1  6.24
    ## 5 Kota Jakarta Bar…  84.4 11.2  3.83e5  3.94  94.9  5.3   2.16  95.7  64.1  6.18
    ## 6 Kota Jakarta Uta…  82.1 10.8  3.80e5  6.44  91.4 30.3   0.52  94.4  67.8  6.18

# Eksplorasi

## Informasi Data

``` r
str(data_anreg)
```

    ## tibble [119 × 11] (S3: tbl_df/tbl/data.frame)
    ##  $ Kabupaten/Kota: chr [1:119] "Kepulauan Seribu" "Kota Jakarta Selatan" "Kota Jakarta Timur" "Kota Jakarta Pusat" ...
    ##  $ Y             : num [1:119] 76.7 87.6 84.8 83.8 84.4 ...
    ##  $ X1            : num [1:119] 9.26 11.95 11.99 11.61 11.24 ...
    ##  $ X2            : num [1:119] 3268 500423 362068 532607 383113 ...
    ##  $ X3            : num [1:119] 13.03 3.03 4.09 4.63 3.94 ...
    ##  $ X4            : num [1:119] 89.1 92.6 97.2 90.3 94.9 ...
    ##  $ X5            : num [1:119] 4.06 1.38 26.73 0.84 5.3 ...
    ##  $ X6            : num [1:119] 0.37 3.74 2.13 0.01 2.16 0.52 3.94 7.72 5.48 6.21 ...
    ##  $ X7            : num [1:119] 93.6 97.3 95.9 96.2 95.7 ...
    ##  $ X8            : num [1:119] 72.6 64.8 64.5 65.1 64.1 ...
    ##  $ X9            : num [1:119] 7.93 5.22 6.95 6.24 6.18 6.18 7.34 7.11 5.99 6.36 ...

``` r
summary(data_anreg)
```

    ##  Kabupaten/Kota           Y               X1               X2        
    ##  Length:119         Min.   :66.72   Min.   : 5.080   Min.   :  3268  
    ##  Class :character   1st Qu.:71.91   1st Qu.: 7.735   1st Qu.: 17677  
    ##  Mode  :character   Median :74.57   Median : 8.330   Median : 28880  
    ##                     Mean   :75.75   Mean   : 8.832   Mean   : 64614  
    ##                     3rd Qu.:78.86   3rd Qu.:10.020   3rd Qu.: 63076  
    ##                     Max.   :89.10   Max.   :12.120   Max.   :532607  
    ##        X3               X4              X5              X6        
    ##  Min.   : 2.340   Min.   :45.88   Min.   : 0.84   Min.   :-1.130  
    ##  1st Qu.: 6.380   1st Qu.:82.23   1st Qu.:10.20   1st Qu.: 3.485  
    ##  Median : 8.980   Median :88.55   Median :19.86   Median : 5.010  
    ##  Mean   : 9.074   Mean   :84.75   Mean   :24.18   Mean   : 4.823  
    ##  3rd Qu.:11.425   3rd Qu.:95.45   3rd Qu.:32.19   3rd Qu.: 6.320  
    ##  Max.   :20.830   Max.   :99.34   Max.   :79.64   Max.   : 9.570  
    ##        X7              X8              X9       
    ##  Min.   :81.59   Min.   :58.13   Min.   :1.560  
    ##  1st Qu.:89.28   1st Qu.:67.99   1st Qu.:3.700  
    ##  Median :92.93   Median :71.92   Median :4.910  
    ##  Mean   :92.27   Mean   :71.58   Mean   :5.026  
    ##  3rd Qu.:95.42   3rd Qu.:74.83   3rd Qu.:6.260  
    ##  Max.   :99.25   Max.   :86.62   Max.   :9.180

1.  Menggunakan Package psych.Cara paling populer di kalangan peneliti
    untuk mendapatkan rangkuman lengkap adalah menggunakan fungsi
    describe() dari package psych.

- sd: Standard Deviation.
- var (opsional di versi tertentu): Jika tidak muncul, Anda bisa
  menghitungnya (SD kuadrat).
- skew: Kemiringan data.
- kurtosis: Keruncingan data.
- se: Standard Error.

``` r
library(psych)
describe(data_anreg)
```

    ##                 vars   n     mean        sd   median  trimmed      mad     min
    ## Kabupaten/Kota*    1 119    60.00     34.50    60.00    60.00    44.48    1.00
    ## Y                  2 119    75.75      5.02    74.57    75.40     4.74   66.72
    ## X1                 3 119     8.83      1.64     8.33     8.78     1.44    5.08
    ## X2                 4 119 64614.02 100110.46 28879.68 40045.02 19694.38 3268.50
    ## X3                 5 119     9.07      3.72     8.98     8.87     3.75    2.34
    ## X4                 6 119    84.75     13.43    88.55    86.72    10.14   45.88
    ## X5                 7 119    24.18     17.31    19.86    22.05    15.18    0.84
    ## X6                 8 119     4.82      2.17     5.01     4.88     2.13   -1.13
    ## X7                 9 119    92.27      3.83    92.93    92.49     4.34   81.59
    ## X8                10 119    71.58      4.67    71.92    71.61     5.10   58.13
    ## X9                11 119     5.03      1.80     4.91     4.98     1.90    1.56
    ##                       max     range  skew kurtosis      se
    ## Kabupaten/Kota*    119.00    118.00  0.00    -1.23    3.16
    ## Y                   89.10     22.38  0.64    -0.52    0.46
    ## X1                  12.12      7.04  0.38    -0.82    0.15
    ## X2              532606.90 529338.40  3.07     9.40 9177.11
    ## X3                  20.83     18.49  0.50    -0.01    0.34
    ## X4                  99.34     53.46 -1.20     0.48    1.23
    ## X5                  79.64     78.80  1.15     1.02    1.59
    ## X6                   9.57     10.70 -0.23    -0.15    0.20
    ## X7                  99.25     17.66 -0.58    -0.37    0.35
    ## X8                  86.62     28.49 -0.01     0.09    0.43
    ## X9                   9.18      7.62  0.24    -0.71    0.16

2.  Menggunakan Package skimr.

Kelebihan skimr:

- Memisahkan rangkuman antara kolom teks dan kolom angka.
- Menampilkan jumlah NA secara jelas.
- Menampilkan SD secara otomatis.
- Ada histogram mini yang menunjukkan distribusi data (apakah data Anda
  menumpuk di angka tinggi atau rendah).

``` r
library(skimr)
skim(data_anreg)
```

|                                                  |            |
|:-------------------------------------------------|:-----------|
| Name                                             | data_anreg |
| Number of rows                                   | 119        |
| Number of columns                                | 11         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |            |
| Column type frequency:                           |            |
| character                                        | 1          |
| numeric                                          | 10         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |            |
| Group variables                                  | None       |

Data summary

**Variable type: character**

| skim_variable  | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:---------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| Kabupaten/Kota |         0 |             1 |   4 |  22 |     0 |      119 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| Y | 0 | 1 | 75.75 | 5.02 | 66.72 | 71.90 | 74.57 | 78.87 | 89.10 | ▃▇▃▃▁ |
| X1 | 0 | 1 | 8.83 | 1.64 | 5.08 | 7.74 | 8.33 | 10.02 | 12.12 | ▁▇▇▃▅ |
| X2 | 0 | 1 | 64614.02 | 100110.46 | 3268.50 | 17676.55 | 28879.68 | 63076.26 | 532606.90 | ▇▁▁▁▁ |
| X3 | 0 | 1 | 9.07 | 3.72 | 2.34 | 6.38 | 8.98 | 11.43 | 20.83 | ▃▇▅▂▁ |
| X4 | 0 | 1 | 84.75 | 13.43 | 45.88 | 82.23 | 88.55 | 95.46 | 99.34 | ▁▁▂▅▇ |
| X5 | 0 | 1 | 24.18 | 17.31 | 0.84 | 10.20 | 19.86 | 32.19 | 79.64 | ▇▇▃▂▁ |
| X6 | 0 | 1 | 4.82 | 2.17 | -1.13 | 3.48 | 5.01 | 6.32 | 9.57 | ▂▃▇▇▃ |
| X7 | 0 | 1 | 92.27 | 3.83 | 81.59 | 89.28 | 92.93 | 95.41 | 99.25 | ▁▅▃▇▅ |
| X8 | 0 | 1 | 71.58 | 4.67 | 58.13 | 67.99 | 71.92 | 74.84 | 86.62 | ▁▆▇▅▁ |
| X9 | 0 | 1 | 5.03 | 1.80 | 1.56 | 3.70 | 4.91 | 6.26 | 9.18 | ▂▇▅▅▂ |

## Data NA

``` r
library(dplyr)
library(tidyr)
colSums(is.na(data_anreg))
```

    ## Kabupaten/Kota              Y             X1             X2             X3 
    ##              0              0              0              0              0 
    ##             X4             X5             X6             X7             X8 
    ##              0              0              0              0              0 
    ##             X9 
    ##              0

DISINI TERLIHAT ADA DATA **na** di Kolom X1-X7

Menghapus semua baris yang punya minimal satu NA

``` r
# Menghapus semua baris yang punya minimal satu NA
data_bersih_anreg = na.omit(data_anreg)
summary(data_bersih_anreg)
```

    ##  Kabupaten/Kota           Y               X1               X2        
    ##  Length:119         Min.   :66.72   Min.   : 5.080   Min.   :  3268  
    ##  Class :character   1st Qu.:71.91   1st Qu.: 7.735   1st Qu.: 17677  
    ##  Mode  :character   Median :74.57   Median : 8.330   Median : 28880  
    ##                     Mean   :75.75   Mean   : 8.832   Mean   : 64614  
    ##                     3rd Qu.:78.86   3rd Qu.:10.020   3rd Qu.: 63076  
    ##                     Max.   :89.10   Max.   :12.120   Max.   :532607  
    ##        X3               X4              X5              X6        
    ##  Min.   : 2.340   Min.   :45.88   Min.   : 0.84   Min.   :-1.130  
    ##  1st Qu.: 6.380   1st Qu.:82.23   1st Qu.:10.20   1st Qu.: 3.485  
    ##  Median : 8.980   Median :88.55   Median :19.86   Median : 5.010  
    ##  Mean   : 9.074   Mean   :84.75   Mean   :24.18   Mean   : 4.823  
    ##  3rd Qu.:11.425   3rd Qu.:95.45   3rd Qu.:32.19   3rd Qu.: 6.320  
    ##  Max.   :20.830   Max.   :99.34   Max.   :79.64   Max.   : 9.570  
    ##        X7              X8              X9       
    ##  Min.   :81.59   Min.   :58.13   Min.   :1.560  
    ##  1st Qu.:89.28   1st Qu.:67.99   1st Qu.:3.700  
    ##  Median :92.93   Median :71.92   Median :4.910  
    ##  Mean   :92.27   Mean   :71.58   Mean   :5.026  
    ##  3rd Qu.:95.42   3rd Qu.:74.83   3rd Qu.:6.260  
    ##  Max.   :99.25   Max.   :86.62   Max.   :9.180

# Pembentukan Model

``` r
y = data_bersih_anreg$Y
x = data_bersih_anreg$X9
n <- nrow(data_bersih_anreg)
```

``` r
b1 = (sum(x*y)-sum(x)*sum(y)/n)/(sum(x^2)-(sum(x)^2/n))
b0 <- mean(y)-b1*mean(x)

cat("Koefisien b0:", b0, "\n")  
```

    ## Koefisien b0: 73.49741

``` r
cat("Koefisien b1:", b1, "\n")
```

    ## Koefisien b1: 0.4473984

## Standar Error Parameter Regresi

Standar error menunjukan seberapa besar ketidakpastian dalam estimasi
koefisien

``` r
galat <- y-(b0+b1*x)
ragam_galat <- sum(galat^2)/(n-2)

se_b0 <- sqrt(ragam_galat*(1/n+mean(x)^2/sum((x-mean(x))^2)))
se_b1 <- sqrt(ragam_galat/sum((x-mean(x))^2))

cat("Standar error b0:", se_b0, "\n") 
```

    ## Standar error b0: 1.357898

``` r
cat("Standar error b1:", se_b1, "\n")
```

    ## Standar error b1: 0.2544849

## Signifikansi Parameter (nilai-t)

Nilai ini menunjukkan tingkat signifikansi secara parsial dari setiap
koefisien peubah berdasarkan nilai t dan probabilitas nilai p

``` r
t_b0 <- b0/se_b0
t_b1 <- b1/se_b1
p_b0 <- 2*pt(-abs(t_b0 ),df<-n-2)
p_b1 <- 2*pt(-abs(t_b1 ),df<-n-2)

cat("Nilai t pada b0 adalah", t_b0, "dengan nilai p sebesar", p_b0, "\n")  
```

    ## Nilai t pada b0 adalah 54.12587 dengan nilai p sebesar 1.150449e-84

``` r
cat("Nilai t pada b1 adalah", t_b1, "dengan nilai p sebesar", p_b1, "\n") 
```

    ## Nilai t pada b1 adalah 1.758055 dengan nilai p sebesar 0.08135316

Nilai p kurang dari alpha 0.05 untuk b0 maupun b1 sehingga signifikan
pada taraf nyata 5%

## Koefisien Determinasi dan Penyesuaiannya

Pada analisis regresi linier sederhana, koefisien determinasi yang
digunakan adalah multiple R Squared, sedangkan regresi linier berganda
menggunakan adjusted R Squared yang disesuaikan dengan banyaknya peubah

``` r
r <- (sum(x*y)-sum(x)*sum(y)/n)/
sqrt((sum(x^2)-(sum(x)^2/n))*(sum(y^2)-(sum(y)^2/n)))
Koef_det <- r^2
Koef_det
```

    ## [1] 0.02573685

``` r
Adj_R2 <- 1-((1-Koef_det)*(n-1)/(n-1-1))
Adj_R2
```

    ## [1] 0.01740982

## Signifikansi Simultan (F)

Nilai ini menunjukkan signifikansi dan kebaikan model secara simultan
(bersamaan seluruh peubah) yang menjelaskan model secara keseluruhan
memiliki hubungan berarti antara X dan Y

``` r
galat<-y-(b0+b1*x)

JKG <- sum((y - (b0+b1*x))^2)
JKReg <- sum(((b0+b1*x)- mean(y))^2)
JKT <- sum((y - mean(y))^2)
JKT <- JKReg+JKG

dbReg <- 1
dbg <- n-2
dbt <- n-1

(Fhit <- (JKReg/dbReg)/(JKG/dbg))
```

    ## [1] 3.090758

``` r
(p_Fhit <- 1-pf(Fhit, dbReg, dbg, lower.tail = F))
```

    ## [1] 0.9186468

Nilai p kurang dari alpha 0.05 sehingga secara simultan X dan Y saling
memengaruhi

## Menggunakan Fungsi `lm()`

Dalam penggunaan fungsi `lm()`, kita akan memperoleh secara langsung
nilai-nilai pada pemodelan regresi dari data yang kita miliki. Hanya
dengan mengeluarkan summary dan anova dari model yang terbentuk maka
dapat diperoleh nilai parameter, signifikansinya, standar eror,
koefisien determinasi hingga ukuran keragamannya.

``` r
model <- lm(Y~X1, data = data_anreg)
summary(model)
```

    ## 
    ## Call:
    ## lm(formula = Y ~ X1, data = data_anreg)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -4.3344 -0.8075  0.0218  1.0481  3.9020 
    ## 
    ## Coefficients:
    ##             Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) 50.35333    0.84613   59.51   <2e-16 ***
    ## X1           2.87498    0.09419   30.52   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 1.683 on 117 degrees of freedom
    ## Multiple R-squared:  0.8884, Adjusted R-squared:  0.8875 
    ## F-statistic: 931.6 on 1 and 117 DF,  p-value: < 2.2e-16

Berdasarkan hasil diperoleh bahwa kedua cara valid dan memberikan hasil
yang sama dalam membuat pemodelan regresi linear sederhana.

``` r
anova(model)
```

    ## Analysis of Variance Table
    ## 
    ## Response: Y
    ##            Df  Sum Sq Mean Sq F value    Pr(>F)    
    ## X1          1 2638.28 2638.28   931.6 < 2.2e-16 ***
    ## Residuals 117  331.34    2.83                      
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# Visualisasi

``` r
boxplot(data_bersih_anreg$Y)
```

![](Anreg_Dama_files/figure-gfm/unnamed-chunk-19-1.png)<!-- -->

``` r
boxplot(data_bersih_anreg$X9)
```

![](Anreg_Dama_files/figure-gfm/unnamed-chunk-20-1.png)<!-- -->

# Kesimpulan

Model yang terbentuk adalah sebagai berikut:

$$\hat{Y} = 73.49741  + 0.4473984   X_1$$
